### ISSUE TITLE
sideEffects: false in package.json

### ISSUE THREAD

**Issue by mtraynham** [d3/d3-transition#100]
This particular commit (https://github.com/d3/d3-transition/commit/6c1c79b8d4de51f886ac8ea9d217eb32aedb561c) adds `sideEffects: false` in the `package.json` file.

For Webpack tree shaking this will essentially remove the modules if they were imported via 
```js
import 'd3-transition';
```

Doesn't d3-transition patch d3-selection as a side effect though?  Is there another intended way to attach transitions to selections?

**Comment by mbostock** [comment]
This was a mistake. I’ll revert.

**Comment by mbostock** [comment]
Fixed in 1.3.2.

**Comment by mtraynham** [comment]
Thanks!

**Comment by mbostock** [comment]
Thanks for the report! This was just a copy-paste error on my part. My eyes kind of glazed over after doing this for 30+ packages…

**Comment by mtraynham** [comment]
No worries!  I pulled the new version and have verified it works correctly.  Thanks again!
