### ISSUE TITLE
transition.end() never resolves if 0 elements are matched

### ISSUE THREAD

**Issue by chahu** [d3/d3-transition#105]
The subject says it all. I was debugging some more complex d3 code and this behavior turned out to be the culprit. Here's a stripped down example.

https://codepen.io/chahu/pen/KKdomVZ

**Comment by Fil** [comment]
In that case no schedule has been set on any node, there is nothing to end. We should probably resolve immediately (as in https://github.com/d3/d3-transition/pull/108), but it might not the behavior you would expect if you'd set a fixed duration.

**Comment by chahu** [comment]
Thanks for looking into this. Based on #108, resolving immediately seems more consistent, but either behavior is reasonable in my eyes.
