### ISSUE TITLE
transition().style() fails to work as expected when applied to a starting property of 0px

### ISSUE THREAD

**Issue by ChrisHSandN** [d3/d3-transition#117]
### Steps to replicate:
1. https://jsfiddle.net/chris_h/4haze3pc/ 
(Note: only Chrome seems to currently support the [SVG2 feature](https://www.w3.org/TR/SVG2/styling.html#PresentationAttributes) of setting geometry properties using CSS style)

### Expected Behaviour
All 4 circles should transition to `cx: 100`

### Actual Behaviour
![image](https://user-images.githubusercontent.com/13466620/94144468-107efb80-fe69-11ea-83bc-41b70b2d8b40.png)

The circle with `style=cx: 0` does not transition to the expected `cx: 100` location.

My best guess is this is due to the browser automatically converting `cx: 0` into `cx: 0px`
![image](https://user-images.githubusercontent.com/13466620/94144703-6489e000-fe69-11ea-9fc8-036b585b2f3f.png)

**Comment by mbostock** [comment]
If you use CSS, you must specify units.

```js
  .style('cx', datum => `${datum.cx}px`)
  .style('cy', datum => `${datum.cy}px`);
```
