### ISSUE TITLE
transition() prevents click events on iOS Safari/15.5

### ISSUE THREAD

**Issue by reacthacker** [d3/d3-transition#138]
In a Safari browser on a mobile phone transition() prevents all click events.
This behavior can be seen more clearly if duration(t) is added to the transition.
Then click events are prevented for the duration of t.

On Desktop-browsers this behavior couldn't be replicated (Safari/Chrome/Firefox).

**Comment by Fil** [comment]
Can you please share a webpage or observable notebook that helps us reproduce the issue? Thank you.

**Comment by reacthacker** [comment]
Not reproducable with observable notebook... probably a problem in own setup with angular
