### ISSUE TITLE
d3.transition and 'stroke-width'

### ISSUE THREAD

**Issue by abusedmedia** [d3/d3-transition#46]
d3.transition doesn't animate 'stroke-width' through style accessor in Chrome and Safari while it does in Firefox.
It works perfectly with ```.attr``` accessor, though.

The same code works well using v3.

Example here:
http://jsbin.com/cuziyaf/edit?html,js,output

**Comment by mbostock** [comment]
CSS property values such as stroke-width require units (e.g., "5px" instead of 5). This is not true of attributes..
