### ISSUE TITLE
Transition behavior is undefined if an error is thrown.

### ISSUE THREAD

**Issue by wlodzislav** [d3/d3-transition#48]
Value function passed to .tween will be called in infinite loop if the last call throws exception.

Code to reproduce:

```js
d3.select("body")
	.transition().duration(1000)
	.tween("crash", function () {
		return function (t) {
			if (t == 0.5) {
				throw "this is fine";
			}

			if (t == 1) {
				throw "infinite loop";
			}
		};
	});

```

**Comment by mbostock** [comment]
I am guessing you don’t mean a literal infinite loop here (that hangs the browser and causes the blue tab of death). You mean that the transition never ends and so the tween is called every tick with t = 1, even though the transition should have ended immediately after the first tick with t = 1.

I guess it would be reasonable to ensure that the transition ends even if an error is thrown on end. Just have to be careful where we put the try-finally for optimization reasons and to preserve the existing state (the transition state is not cleared until after the transition ends).

**Comment by mbostock** [comment]
Confirmed that this is not an infinite loop (and that the transition doesn’t end):

http://bl.ocks.org/mbostock/93b26626ac948365fe8efb3ff054c204

Related d3/d3#2415. There are potentially a bunch of issues here, though some of the following behaviors may be reasonable:

1. If an error is thrown by an interrupt event listener when a transition starts, the interrupted transition is never cleaned up and the starting transition never starts. 
1. If an error is thrown by a start event listener, the transition does not finish starting nor is it cleaned up.
1. If a tween throws an error on start, subsequent tweens are never initialized and will not be invoked for the duration of the transition. 
1. If a tween throws an error on tick, subsequent tweens are not invoked for that tick (nor are subsequent timers).
1. If a tween throws an error on the last tick, the transition does not finish ending nor is it cleaned up.
1. If an error is thrown by an end event listener, the transition is not cleaned up.

I don’t think the answer is to wrap every listener and tween invocation if a try block, but I do think we can probably define better behavior when errors are thrown.
