### ISSUE TITLE
Setting <path> d attribute to null via attrTween causes error. Seems null becomes "null"

### ISSUE THREAD

**Issue by pbeshai** [d3/d3-transition#56]
When setting a <path> element's d attribute to null via `.attr('d', null)`, there is no error. But if using an interpolator that returns `null` at some point via attrTween an error occurs. It seems the cause is that `null` becomes the string `"null"`

```js
d3.select('path').transition().attrTween('d', d => () => null)
```

The above code produces the error:
![image](https://cloud.githubusercontent.com/assets/793847/18172332/fc4dd668-7032-11e6-9fe7-f0622f1d24ea.png)

This code works fine:
```js
d3.select('path').attr('d', null)
```

This code produces a similar error (which seems fine to me):
```js
d3.select('path').attr('d', 'null')
```

![image](https://cloud.githubusercontent.com/assets/793847/18172400/36879ae4-7033-11e6-8219-ee17b5b72f67.png)

Using http://d3js.org/d3.v4.js

**Comment by pbeshai** [comment]
On further inspection:
```js
document.querySelector('path').setAttribute('d', null)
```
VM11325:1 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "null".

**Comment by pbeshai** [comment]
You make a good point about the overhead of checking for this case. I was just surprised to find that it operated differently from `attr`-- I figured they were equivalent. 

Here is one use case: I have a path string "M0,0L1,0" that is going interpolate to `null` via my interpolator. My interpolator will return all the intermediate values to make the animation work, but at the end, the interpolator(1) returns `null`, which would cause the error. I could have the interpolator swap nulls with empty strings to avoid the error.

**Comment by mbostock** [comment]
Yeah, I agree it’s inconsistent with *transition*.attr, but perhaps it’s better to think of it like `d3.interpolateString("M0,0L1,0", null)` which returns `"null"` for all values.

**Comment by mbostock** [comment]
Another way to implement this is to use *transition*.tween and then call *node*.setAttribute and *node*.removeAttribute yourself, though admittedly that’s a bit more tedious. See [attrTween.js](https://github.com/d3/d3-transition/blob/master/src/transition/attrTween.js) for hints.

**Comment by pbeshai** [comment]
Thanks for clarifying:
> Lastly, the return value of the interpolator will be used to set the attribute value. The interpolator must return a string.

I'll update my interpolator accordingly.

**Comment by gaiagilder** [comment]
Same thing here but only with chrome, no errors in Firefox and no problems with the animation, in chrome lack a bit at starting instead,

    svg.selectAll("path")
      .transition()
      .duration(1000)
      .attrTween("d", function(d) {
    
        var r = d3.interpolate(currentRotate, nextRotate);
        var s = d3.interpolate(currentScale, nextScaleRatio*currentScale);
        return function(t) {
          projection.scale(s(t)).rotate(r(t));
          pathD = path(d);
          return pathD!=null?pathD:""; 
        }  
    });
