### ISSUE TITLE
Transition throwing 'too late' error in react

### ISSUE THREAD

**Issue by noahehall** [d3/d3-transition#63]
playing around with transitions for a  udacity project, and i started getting these 'too late' errors when overing over a bar chart

relavant code is here:
https://github.com/noahehall/udacity-corporate-dashboard/blob/piecharts/src/components/charts/examples.js#L155

error im getting:
![screen shot 2016-12-15 at 9 00 42 am](https://cloud.githubusercontent.com/assets/10324554/21233708/ffa7f6da-c2a4-11e6-928f-420ceeb627c7.png)

**Comment by mbostock** [comment]
This means you are trying to modify a transition that has already started, or derive a transition from one that has ended. Please read the API Reference section on transition life cycles.

**Comment by noahehall** [comment]
thanks @mbostock
