### ISSUE TITLE
Tweens keep tweening after new transition is fired or .interrupt called

### ISSUE THREAD

**Issue by phocks** [d3/d3-transition#75]
I've noticed that the .tween function keeps on going even after a new transition is fired. I've seen people suggest that to stop a transition in its tracks simply fire a new transition, however I've noticed that the new transition fires and the tween function still counts up the *time* when console logged and it just runs those tweens concurrently.

I have also just tried using .interrupt() and it doesn't seem to stop the tween either. I'm just wondering if there is possibly something I'm missing, or if stopping these tweens from firing multiple times is just impossible at the moment.

**Comment by mbostock** [comment]
Do you have an example you can link to that demonstrates the issue?

**Comment by phocks** [comment]
Hmm that's interesting. I just built this quick demo and the functionality I am seeing in my full project is not happening and it seems to be cancelling the tween with the transition.

Here's the demo. Open the console and you can see that if you click the button multiple times it seems to override the tween's time output and starts counting from 0 again.

https://glitch.com/edit/#!/tween-demo https://tween-demo.glitch.me/

But back in my app it is not cancelling out the previous tween and you end up get multiple number 1's

![snip20170928_4](https://user-images.githubusercontent.com/437566/30943720-342fbf14-a436-11e7-9346-0c3ea36132bd.png)

Looks like this is some kind of issue with my code then... so feel free to disregard and close this. Thanks so much for responding so quickly too! Good work on D3 I love it!

**Comment by mbostock** [comment]
Okay, closing as I have no means of investigating. My guess is that perhaps your transitions are being scheduled on different elements, and so are not exclusive with respect to each other.
