### ISSUE TITLE
interrupt should cancel all scheduled transitions, too.

### ISSUE THREAD

**Issue by mbostock** [d3/d3-transition#9]
The recommended pattern for interrupting any active transition and canceling any schedule transition is:

```js
selection
    .interrupt()
    .transition();
```

However, note that this does not have the desired effect if the transition that is used to cancel scheduled transition is subsequently modified via transition.each:

```js
selection
    .interrupt()
    .transition()
    .each(function() { d3.select(this).transition().delay(750); }); // oops!
```

Possibly, selection.interrupt should automatically cancel any scheduled transitions (a non-backwards-compatible change). I can’t think of many cases where you don’t want to cancel scheduled transitions when interrupting, but given that I didn’t already implement it this way I wonder if I’m overlooking something, or if the current behavior was simply done because it was the easiest to implement and I thought that scheduling a no-op transition was sufficient (and also common).

Alternatively, we could introduce a new selection.cancel method. Would this only clear scheduled but not-yet-active transitions, or would it also interrupt the active transition?

**Comment by mbostock** [comment]
Related mbostock/d3#2189.

**Comment by mbostock** [comment]
Related d3/d3-timer#5, in that an explicit cancel (or expanded interrupt) operation could also *synchronously* cancel all scheduled transitions, rather than waiting until their first tick to self-terminate. Thus, after a call to selection.interrupt you could guarantee that `node.__transition__` is null.

**Comment by mbostock** [comment]
Yet another nice thing about synchronously canceling transitions is that transition.remove can easily check whether there’s another valid transition scheduled (mbostock/d3#2377).

**Comment by mbostock** [comment]
Yet another reason that selection.interrupt should cancel scheduled transitions is that, in 3.x, this confusingly doesn’t cancel the new transition:

```js
selection.transition(); // schedule a new transition (that will start in one tick)
selection.interrupt(); // doesn’t cancel the above transition, because it hasn’t yet started
```

**Comment by LaceaNix** [comment]
Thank you! I am have more then enough problems with my iPhone and it's caused me to lose everything. I'm positive my phone is hacked..in which is causing delayed and or missed calls. Can you help me?

**Comment by mbostock** [comment]
Done.
